/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from 'ack-angular/pipes';
import * as i2 from '@angular/platform-browser';
import * as i3 from '../../../src/rjon/components';
import * as i4 from './components.ngfactory';
const styles_RjonLinks:any[] = ([] as any[]);
export const RenderType_RjonLinks:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_RjonLinks,
    data:{}});
export function View_RjonLinks_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵpid(0,i1.SafeUrl,[i2.DomSanitizer]),i0.ɵpid(0,i1.TextDownload,
      ([] as any[])),(_l()(),i0.ɵeld(0,(null as any),(null as any),11,'div',[['class',
      'pad-v child-margin-xs']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a',([] as any[]),
      [[8,'href',4]],(null as any),(null as any),(null as any),(null as any))),i0.ɵppd(1),
      (_l()(),i0.ɵted((null as any),['email json'])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),3,'a',[['download','rjon.json']],[[8,'href',4]],(null as any),
          (null as any),(null as any),(null as any))),i0.ɵppd(1),i0.ɵppd(1),(_l()(),
          i0.ɵted((null as any),['download json'])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),3,'a',[['download','rjon.md']],[[8,'href',4]],(null as any),
          (null as any),(null as any),(null as any))),i0.ɵppd(1),i0.ɵppd(1),(_l()(),
          i0.ɵted((null as any),['download markdown']))],(null as any),(_ck,_v) => {
    var _co:i3.RjonLinks = _v.component;
    const currVal_0:any = i0.ɵunv(_v,3,0,_ck(_v,4,0,i0.ɵnov(_v,0),_co.getEmailString()));
    _ck(_v,3,0,currVal_0);
    const currVal_1:any = i0.ɵunv(_v,6,0,_ck(_v,8,0,i0.ɵnov(_v,0),i0.ɵunv(_v,6,0,_ck(_v,
        7,0,i0.ɵnov(_v,1),_co.getDownloadString()))));
    _ck(_v,6,0,currVal_1);
    const currVal_2:any = i0.ɵunv(_v,10,0,_ck(_v,12,0,i0.ɵnov(_v,0),i0.ɵunv(_v,10,
        0,_ck(_v,11,0,i0.ɵnov(_v,1),_co.getMarkdownString()))));
    _ck(_v,10,0,currVal_2);
  });
}
export function View_RjonLinks_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'rjon-links',([] as any[]),
      (null as any),(null as any),(null as any),i4.View_RjonLinks_0,i4.RenderType_RjonLinks)),
      i0.ɵdid(49152,(null as any),0,i3.RjonLinks,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const RjonLinksNgFactory:i0.ComponentFactory<i3.RjonLinks> = i0.ɵccf('rjon-links',
    i3.RjonLinks,View_RjonLinks_Host_0,{rjon:'rjon'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Fja2VyYXBwbGUvcHJvamVjdHMvQWNrL2Jyb3dzZXIvcmpvbi9hcHAvc3JjL3Jqb24vY29tcG9uZW50cy5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hY2tlcmFwcGxlL3Byb2plY3RzL0Fjay9icm93c2VyL3Jqb24vYXBwL3NyYy9yam9uL2NvbXBvbmVudHMuZC50cyIsIm5nOi8vL1VzZXJzL2Fja2VyYXBwbGUvcHJvamVjdHMvQWNrL2Jyb3dzZXIvcmpvbi9hcHAvc3JjL3Jqb24vY29tcG9uZW50cy5kLnRzLlJqb25MaW5rcy5odG1sIiwibmc6Ly8vVXNlcnMvYWNrZXJhcHBsZS9wcm9qZWN0cy9BY2svYnJvd3Nlci9yam9uL2FwcC9zcmMvcmpvbi9jb21wb25lbnRzLmQudHMuUmpvbkxpbmtzX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cInBhZC12IGNoaWxkLW1hcmdpbi14c1wiPjxhIFtocmVmXT1cImdldEVtYWlsU3RyaW5nKCkgfCBzYWZlVXJsXCI+ZW1haWwganNvbjwvYT48YSBbaHJlZl09XCJnZXREb3dubG9hZFN0cmluZygpIHwgdGV4dERvd25sb2FkIHwgc2FmZVVybFwiIGRvd25sb2FkPVwicmpvbi5qc29uXCI+ZG93bmxvYWQganNvbjwvYT48YSBbaHJlZl09XCJnZXRNYXJrZG93blN0cmluZygpIHwgdGV4dERvd25sb2FkIHwgc2FmZVVybFwiIGRvd25sb2FkPVwicmpvbi5tZFwiPmRvd25sb2FkIG1hcmtkb3duPC9hPjwvZGl2PiIsIjxyam9uLWxpbmtzPjwvcmpvbi1saW5rcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7cUJDQUE7TUFBQTtNQUFBLGdCQUFtQztNQUFBLGdGQUFHO01BQW9DLCtDQUFjO1VBQUE7VUFBQSxtREFBRyxlQUEyRTtpQkFBQSxtQ0FBaUI7VUFBQTtVQUFBLG1EQUFHLGVBQXlFO2lCQUFBOztJQUE3TjtJQUFILFdBQUcsU0FBSDtJQUF3RDtRQUFBO0lBQUgsV0FBRyxTQUFIO0lBQWtHO1FBQUE7SUFBSCxZQUFHLFNBQUg7Ozs7b0JDQXZMO01BQUE7YUFBQTs7OzsifQ==
